apiVersion: v1
kind: Service
metadata:
  name: reliabilityhub-api
  namespace: reliabilityhub-system
  labels:
    app: reliabilityhub-api
spec:
  selector:
    app: reliabilityhub-api
  ports:
    - name: http
      port: 9090
      targetPort: http
  type: ClusterIP
