apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reliabilityhub-system
resources:
  - ../../base/api
  - ../../base/web
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: reliabilityhub-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: reliabilityhub-web
images:
  - name: localhost:5001/reliabilityhub-api
    newTag: v0.4.0
